-- Commando Staging — personal PostgreSQL user per developer
-- Step 1: connect as master user shuli_admin to database "postgres"
-- Step 2: run "CREATE DATABASE" section
-- Step 3: connect to database "commando_dev" and run the rest
--
-- Replace each CHANGE_ME_* with a unique strong password.
-- Send each developer ONLY their username + password (private message).

-- === On database: postgres ===
CREATE DATABASE commando_dev;

-- === On database: commando_dev ===

-- Avigail8532
CREATE USER dev_avigail WITH PASSWORD 'AVIGAIL_avigail';
GRANT CONNECT ON DATABASE commando_dev TO dev_avigail;
GRANT USAGE ON SCHEMA public TO dev_avigail;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO dev_avigail;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO dev_avigail;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dev_avigail;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO dev_avigail;

-- HilaGeula
CREATE USER dev_hila WITH PASSWORD 'HILA_hila';
GRANT CONNECT ON DATABASE commando_dev TO dev_hila;
GRANT USAGE ON SCHEMA public TO dev_hila;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO dev_hila;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO dev_hila;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dev_hila;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO dev_hila;

-- MalkyDoutsch
CREATE USER dev_malky WITH PASSWORD 'MALKY_malky';
GRANT CONNECT ON DATABASE commando_dev TO dev_malky;
GRANT USAGE ON SCHEMA public TO dev_malky;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO dev_malky;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO dev_malky;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dev_malky;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO dev_malky;

-- SaraDinaKelerman
CREATE USER dev_sara WITH PASSWORD 'SARA_sara';
GRANT CONNECT ON DATABASE commando_dev TO dev_sara;
GRANT USAGE ON SCHEMA public TO dev_sara;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO dev_sara;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO dev_sara;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dev_sara;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO dev_sara;

-- shirasiroka
CREATE USER dev_shira WITH PASSWORD 'SHIRA_shira';
GRANT CONNECT ON DATABASE commando_dev TO dev_shira;
GRANT USAGE ON SCHEMA public TO dev_shira;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO dev_shira;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO dev_shira;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dev_shira;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO dev_shira;

-- Ayala
CREATE USER dev_ayala WITH PASSWORD 'AYALA_ayala';
GRANT CONNECT ON DATABASE commando_dev TO dev_ayala;
GRANT USAGE ON SCHEMA public TO dev_ayala;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO dev_ayala;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO dev_ayala;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dev_ayala;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO dev_ayala;

-- Verify
SELECT usename FROM pg_user WHERE usename LIKE 'dev_%' ORDER BY usename;
